#!/bin/bash

# Establece el puerto por defecto
puerto=4444

# Verifica si se ha proporcionado un argumento para el puerto
if [ ! -z "$1" ]; then
    puerto=$1
fi

# Verifica que el puerto sea un número válido
if ! [[ "$puerto" =~ ^[0-9]+$ ]]; then
    echo "Error: El puerto debe ser un número entero."
    exit 1
fi

# Ejecuta el comando con el puerto especificado
sudo rlwrap nc -lvnp "$puerto"
