#!/bin/bash

# Verificar que se haya proporcionado un argumento
if [ "$#" -ne 1 ]; then
  echo "Uso: $0 <dirección IP>"
  exit 1
fi

# Obtener la dirección IP del argumento
IP_ADDRESS=$1

# Ejecutar el comando rustscan con los parámetros proporcionados
rustscan -a "$IP_ADDRESS" --ulimit 5000 -- --min-rate 5000 -sCV -Pn -T4
